src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"}, message="Un compte existe déjà avec ce email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $organization;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $kbis;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $user_token;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $api_access_token;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_validated;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return null|String 
     */
    public function getEmail(): ?String
    {
        return $this->email;
    }

    /**
     * @param String $email 
     * @return User 
     */
    public function setEmail(String $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): String
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): String
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param array $roles 
     * @return User 
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): String
    {
        return $this->password;
    }

    /**
     * @param String $password 
     * @return User 
     */
    public function setPassword(String $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?String
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return null|String 
     */
    public function getName(): ?String
    {
        return $this->name;
    }

    /**
     * @param null|String $name 
     * @return User 
     */
    public function setName(?String $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return null|String 
     */
    public function getFirstName(): ?String
    {
        return $this->first_name;
    }

    /**
     * @param null|String $first_name 
     * @return User 
     */
    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    /**
     * @return null|String 
     */
    public function getOrganization(): ?String
    {
        return $this->organization;
    }

    /**
     * @param null|String $organization 
     * @return User 
     */
    public function setOrganization(?String $organization): self
    {
        $this->organization = $organization;

        return $this;
    }

    /**
     * @return null|String 
     */
    public function getKbis(): ?String
    {
        return $this->kbis;
    }

    /**
     * @param null|String $kbis 
     * @return User 
     */
    public function setKbis(?String $kbis): self
    {
        $this->kbis = $kbis;

        return $this;
    }

    /**
     * @return null|String 
     */
    public function getPhone(): ?String
    {
        return $this->phone;
    }

    /**
     * @param String $phone 
     * @return User 
     */
    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return null|String 
     */
    public function getUserToken(): ?String
    {
        return $this->user_token;
    }

    /**
     * @param null|String $user_token 
     * @return User 
     */
    public function setUserToken(?String $user_token): self
    {
        $this->user_token = $user_token;

        return $this;
    }

    /**
     * @return null|String 
     */
    public function getApiAccessToken(): ?String
    {
        return $this->api_access_token;
    }

    /**
     * @param null|String $api_access_token 
     * @return User 
     */
    public function setApiAccessToken(?String $api_access_token): self
    {
        $this->api_access_token = $api_access_token;

        return $this;
    }

    /**
     * @return null|bool 
     */
    public function getIsValidated(): ?bool
    {
        return $this->is_validated;
    }

    /**
     * @param bool $is_validated 
     * @return User 
     */
    public function setIsValidated(bool $is_validated): self
    {
        $this->is_validated = $is_validated;

        return $this;
    }

    /**
     * @return null|DateTimeImmutable 
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    /**
     * @ORM\PrePersist
     * @return User 
     */
    public function setCreatedAt(): self
    {
        if ($this->created_at === null) {
            $this->created_at = new \DateTimeImmutable('now');
        }
        return $this;
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Form\ContactType;
use App\Service\Security\TokenService;
use App\Service\Email\EmailService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Service\Security\ApiTokenAccessService;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;

class FrontController extends AbstractController
{
    private $mailer;

    public function __construct(EmailService $mailer)
    {
        $this->mailer = $mailer;
    }

    /**
     * @Route("/", name="home")
     */
    public function home(TokenService $tokenService, ApiTokenAccessService $apiTokenAccessService, Request $request): Response
    {
        $form = $this->createForm(ContactType::class);

        // Récupération des données du contact form + envoi de mail
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $this->mailer->sendContactEmail($data);
            $this->addFlash('success', 'Votre message a bien été envoyé.');
        }

        // dd($apiTokenAccessService->generateApiAccessToken());
        return $this->render('front/home.html.twig', [
            'contactForm' => $form->createView()
        ]);
    }
}

templates/include/front/_footer.html.twig
<footer id="l-footer">
    <section id="brand-informations">
        <div id="l-constrained">
            <div class="brand___contact">
                <div class="adresse">
                    <i class='bx bx-map'></i>
                    <a 
                    href="https://www.google.fr/maps/place/Need+for+School/@49.4303564,1.0808759,19.62z/data=!4m5!3m4!1s0x47e0df1548cd768b:0x70b4b34959b1ec9f!8m2!3d49.4304007!4d1.0812127"
                    target="_blank">
                        Place Henri Gadeau de Kerville,<br>76100 Rouen
                    </a>
                </div>
                <div class="phone">
                    <i class='bx bx-phone-call' ></i>
                    <a href="tel:+33607080910">06.07.08.09.10</a>
                </div>
                <div class="email">
                    <i class='bx bx-envelope' ></i>
                    <a href="mailto:contact@benaverre.fr">contact@benaverre.fr</a>
                </div>
            </div>
            <div class="brand___logo">
                <a href="{{ path('home') }}"><img src="{{ asset('assets/images/logo.png') }}" alt="logo du site"></a>
            </div>
            <div class="brand___about">
                <h3 class="subtitle">A Propos</h3>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque libero architecto eveniet? Quibusdam fuga eius magni 
                    quaerat sapiente vitae, beatae nesciunt tempora consectetur explicabo! Mollitia assumenda id saepe excepturi doloremque 
                    accusantium debitis soluta incidunt asperiores.</p>
                <div class="brand__social-link">
                    <a href="https://instagram.com" target="_blank" class="instagram"><i class='bx bxl-instagram'></i></a>
                    <a href="https://facebook.com" target="_blank" class="facebook"><i class='bx bxl-facebook'></i></a>
                    <a href="https://twitter.com" target="_blank" class="twitter"><i class='bx bxl-twitter'></i></a>
                </div>
            </div>
        </div>
    </section>
    <div class="copyright">
        <div id="l-constrained">
            <p>&copy; Copyright 2021 Ben a verre | Tous droits réservés</p>
        </div>
    </div>
</footer>

templates/include/front/_header.html.twig
<div id="js_overlay" class="overlay" aria-hidden="true"></div>
<header id="l-header">
    <div id="l-constrained">
        <nav>
            <div class="logo">
                <a href="{{ path('home') }}"><img src="{{ asset('assets/images/logo.png') }}" alt="logo du site"></a>
            </div>
            <ul class="link-list">
                <li><a href="{{ path('home') }}">Accueil</a></li>
                <li><a href="{{ path('home', {'_fragment': 'trouver-une-benne'}) }}">Trouver une benne</a></li>
                <li><a href="{{ path('home', {'_fragment': 'contact'}) }}">Contact</a></li>
            </ul>
            <ul class="btn-list">
                {% if is_granted('ROLE_USER') %}
                    <li class="has-submenu">
                        <a title="Mon compte" href="javascript:void(0);"><i class='bx bx-user-circle' ></i></a>
                        <ul class="submenu">
                            <li class="display-name">Bonjour, <span>{{ app.user.firstName }} {{ app.user.name }}</span></li>
                            <li><a href="{{ path('my-account') }}">Mon compte</a></li>
                            <li><a class="logout-btn" href="{{ path('app_logout') }}">Déconnexion</a></li>
                        </ul>
                    </li>
                {% else %}        
                    <li><a href="{{ path('app_login') }}">Connexion</a></li>
                    <li><a href="{{ path('app_inscription') }}" class="btn btn-primary">Inscription</a></li>
                {% endif %}
            </ul>

            {# Responsive Menu START #}
            <ul id="js_reponsive-list" class="responsive-list" aria-expanded="false">
                <li><a href="{{ path('home') }}">Accueil</a></li>
                <li><a href="{{ path('home') }}#trouver-une-benne">Trouver une benne</a></li>
                <li><a href="{{ path('home') }}#contact">Contact</a></li>
                {% if is_granted('ROLE_USER') %}
                <li class="has-submenu">
                    <a href="javascript:void(0);">Mon compte <i class='bx bx-chevron-down' ></i></a>
                    <ul class="submenu">
                        <li class="display-name">Bonjour, <span>{{ app.user.firstName }} {{ app.user.name }}</span></li>
                        <li><a href="{{ path('my-account') }}">Voir mon compte</a></li>
                        <li><a class="logout-btn" href="{{ path('app_logout') }}">Déconnexion</a></li>
                    </ul>
                </li>
                {% else %}
                    <li><a href="#">Connexion</a></li>
                    <li><a href="#" class="btn btn-primary">Inscription</a></li>
                {% endif %}
            </ul>
            <div id="js_hamburger" class="hamburger">
                <span class="bar bar-top"></span>
                <span class="bar bar-middle"></span>
                <span class="bar bar-bottom"></span>
            </div>
            {# Responsive Menu END #}
        </nav>
    </div>
</header>